### ISSUE TITLE
Error after module update

### ISSUE THREAD

**Issue by felixhahnweilheim** [humhub-contrib/gallery#122]
After updating to the latest module version I get the error (see below) in the logs.
The mentioned file is present and belongs to the www-data user.
I don't see any other errors and the module seems still to work. I just wanted to report this.

HumHub v1.14.0
production site
PHP 8.0

```
yii\base\ErrorException: include(/var/www/humhub/protected/modules/gallery/config.php): Failed to open stream: No such file or directory in /var/www/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php:77
Stack trace:
#0 /var/www/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(77): yii\base\ErrorHandler->handleError()
#1 /var/www/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(77): include()
#2 /var/www/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(48): humhub\components\bootstrap\ModuleAutoLoader::findModules()
#3 /var/www/humhub/protected/humhub/components/bootstrap/ModuleAutoLoader.php(34): humhub\components\bootstrap\ModuleAutoLoader::locateModules()
#4 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(325): humhub\components\bootstrap\ModuleAutoLoader->bootstrap()
#5 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(271): yii\base\Application->bootstrap()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#7 /var/www/humhub/protected/humhub/components/console/Application.php(94): yii\console\Application->init()
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\components\console\Application->init()
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct()
#11 /var/www/humhub/protected/humhub/components/console/Application.php(52): yii\console\Application->__construct()
#12 /var/www/humhub/protected/yii(28): humhub\components\console\Application->__construct()
#13 {main}
```

**Comment by felixhahnweilheim** [comment]
Yes, it was triggered during (or shortly after) updating a row of modules with the "Update all" button.
It's very unlikely someone accessed the gallery the same time.

I just downgraded the module manually to version 1.5.2 and did the update to 1.5.3 again. This time no error occured. So maybe it was just some server problem exactly at the same time.
